### ISSUE TITLE
[1.9.4] Crash Shift cliking items onto the Void Bag

### ISSUE THREAD

**Issue by MrAmericanMike** [lorddusk/Bagginses#46]
Using version Bagginses-1.9.4-2.4.2b when I shift click items into the Void Bag, the mod crashes.

`[15:37:55] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1712) ~[bcd.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) ~[bcd.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369) [bcd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at nl.lang2619.bagginses.references.BlockList.contains(BlockList.java:45) ~[BlockList.class:?]
	at nl.lang2619.bagginses.items.bags.container.BagContainer$SlotBag.func_75214_a(BagContainer.java:271) ~[BagContainer$SlotBag.class:?]
	at nl.lang2619.bagginses.items.bags.container.BagContainer.tryShiftItem(BagContainer.java:172) ~[BagContainer.class:?]
	at nl.lang2619.bagginses.items.bags.container.BagContainer.transferVoid(BagContainer.java:147) ~[BagContainer.class:?]
	at nl.lang2619.bagginses.items.bags.container.BagContainer.func_82846_b(BagContainer.java:136) ~[BagContainer.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:258) ~[aau.class:?]
	at nl.lang2619.bagginses.items.bags.container.BagContainer.func_184996_a(BagContainer.java:231) ~[BagContainer.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:540) ~[bkr.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630) ~[bfr.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389) ~[bfr.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540) ~[bez.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509) ~[bez.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1699) ~[bcd.class:?]
	... 17 more`

I was shift clicking 1 stack of spruce wood planks

PS: Any item you try to place on the void bag, crash the mod.

**Comment by AKTheKnight** [comment]
Thanks for reporting this. I can see what's causing the issue and I just need to find a fix for it.

(For reference: Checking whitelist on void bag crashes everything)

**Comment by lorddusk** [comment]
that's why it used to never check it since it has its own slot class...

**Comment by AKTheKnight** [comment]
I haven't changed it, but the isItemValid was breaking

**Comment by AKTheKnight** [comment]
@MrAmericanMike This has been fixed in 2.4.2c (Available on curseforge) Thanks for reporting it :)
