### ISSUE TITLE
Exception when breaking blocks, this log was generated when using a TIC Hammer.

### ISSUE THREAD

**Issue by AlgorithmX2** [lorddusk/Bagginses#53]
```
[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent@5ed82490:
java.lang.NullPointerException
at nl.lang2619.bagginses.event.ItemDropEvent.onBlockDrops(ItemDropEvent.java:50)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_278_ItemDropEvent_onBlockDrops_HarvestDropsEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:213)
at net.minecraft.block.Block.func_180653_a(Block.java:545)
at net.minecraft.block.Block.func_176226_b(Block.java:537)
at net.minecraft.block.BlockReed.func_176353_e(BlockReed.java:116)
at net.minecraft.block.BlockReed.func_189540_a(BlockReed.java:105)
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)
at net.minecraft.world.World.func_180496_d(World.java:517)
at net.minecraft.world.World.func_175685_c(World.java:466)
at net.minecraft.world.World.func_175722_b(World.java:421)
at net.minecraft.world.World.markAndNotifyBlock(World.java:366)
at net.minecraft.world.World.func_180501_a(World.java:347)
at net.minecraft.block.Block.removedByPlayer(Block.java:1106)
at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:275)
at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:333)
at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:220)
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631)
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40)
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10)
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
```

**Comment by lorddusk** [comment]
https://github.com/lorddusk/Bagginses/blob/1.10/src/main/java/nl/lang2619/bagginses/event/ItemDropEvent.java#L50

Proper testing is required, this shouldn't NPE at all.

**Comment by lorddusk** [comment]
Fixed in https://github.com/lorddusk/Bagginses/commit/683c47d212aa4f6ea67c2a07a7bd2d0b1b717b03
