### ISSUE TITLE
3.0.0b crash when mousing over bag in JEI

### ISSUE THREAD

**Issue by eractnod** [lorddusk/Bagginses#57]
When hovering mouse over any bag in JEI, get an ArrayIndexOutOfBoundsException: 1 error.  Thought it might have to do with naming bags, but it crashed even hovering over a named bag.  The rest of the error.
Version 3.0.0a does not have this error.

	at nl.lang2619.bagginses.items.bags.Bag.func_77624_a(Bag.java:130)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:610)
	at mezz.jei.gui.ingredients.GuiItemStackFast.getTooltip(GuiItemStackFast.java:216)
	at mezz.jei.gui.ingredients.GuiItemStackFast.drawTooltip(GuiItemStackFast.java:209)
	at mezz.jei.gui.ItemListOverlay.drawTooltips(ItemListOverlay.java:348)
	at mezz.jei.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:109)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_404_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:375)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by AKTheKnight** [comment]
Thanks for reporting this. A silly mistake by me that didn't show up in testing. Fixes have been pushed to curse (1.9.4-2.5.0c    1.10-3.0.0c) but are waiting to be approved.

You can grab latest builds from here in the mean time: http://jenkins.aktheknight.co.uk/view/Bagginses/

**Comment by AKTheKnight** [comment]
Fixed in b76c766e06686ac257d394248ec887c84bf7d0ca

**Comment by eractnod** [comment]
Thank you sir.  Rev C working like a champ.

**Comment by AKTheKnight** [comment]
Glad to hear it. Thanks again for reporting it :)
