### ISSUE TITLE
[1.10.2] Server Crash - DropEvent.doStacksMatch

### ISSUE THREAD

**Issue by ProsperCraft** [lorddusk/Bagginses#75]
http://pastebin.com/3NKehN5j

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at nl.lang2619.bagginses.event.ItemDropEvent.doStacksMatch(ItemDropEvent.java:144)
	at nl.lang2619.bagginses.event.ItemDropEvent.onBlockDrops(ItemDropEvent.java:119)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_624_ItemDropEvent_onBlockDrops_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:228)
	at net.minecraft.block.Block.func_180653_a(Block.java:545)
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:230)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1175)
	at net.minecraft.world.World.func_72876_a(World.java:2303)
	at net.minecraft.entity.monster.EntityCreeper.func_146077_cc(SourceFile:243)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:154)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ProsperCraft** [comment]
thejims - Today at 4:12 PM
@Goshen I had issues earlier with my baggins bag after starky crashed the server.  In pickup mode it wasn't picking up items and in default mode it was voiding all items..

**Comment by AKTheKnight** [comment]
Hmm, thanks for reporting this to me. I think I can see the issue and I should be able to get a fix out tomorrow (It's also shown another issue I need to fix too)

**Comment by AKTheKnight** [comment]
I've just posted 3.0.4d on curseforge (waiting for approval) and it should fix the issue. Let me know if it doesn't work :)

**Comment by tivec** [comment]
I am playing with 3.0.4d in the AllTheMods pack, and I just had this crash happen on my server as well. Here's my trace: https://gist.github.com/anonymous/35b4e8c7e90ee39fd25873e03792e1b9

**Comment by AKTheKnight** [comment]
Huh. The code I fixed it with wasn't pushed for some reason. I'll fix it in a sec :)

**Comment by AKTheKnight** [comment]
3.0.4e is up on curseforge and should fix the issue (I was unable to reproduce it so had to work backwards to try and fix it)
